### ISSUE TITLE
How to use middleware.requireUser?

### ISSUE THREAD

**Issue by molda** [danielpquinn/keystone-rest#7]
I was just wondering if there is any recommended way to protect api routes?
req.user is undefined in registerRoutes so can't do 
```javascript
app[route.method](route.route, middleware.requireUser, route.handler);
```
and i don't see keystone's log for routes added this way
so i do following instead of keystoneRest.registerRoutes(...);
```javascript
keystone.apiRoutes = keystone.apiRoutes || [];
keystone.apiRoutes.push(keystoneRest);
```
and then in routes/index.js when req.user is defined
```javascript
keystone.apiRoutes.forEach(function(keystoneRest) {
  keystoneRest.registerRoutes(keystone.app, middleware.requireUser);
});
```
this obviously need a change in reqisterRoutes function
```javascript
    this.registerRoutes = function(app, requireUser) {
        _.each(this.routes, function(route) {
            if(requireUser){
                app[route.method](route.route, requireUser, route.handler);
            }else{
                app[route.method](route.route, route.handler);
            }            
        });
    };
```
So is there any other/better way to achieve this or am i missing something?

**Comment by danielpquinn** [comment]
Hi molda,

I pushed an update to the package that allows you to add middleware on a per-route basis. For example:

    keystoneRest.addRoutes(Post, 'show list', { list: [middleware.requireUser] });

This will execute middleware.requireUser before listing posts.

**Comment by molda** [comment]
Hi danielpquinn that's awesome thank you
