### ISSUE TITLE
Security & Pagination

### ISSUE THREAD

**Issue by Industrial** [danielpquinn/keystone-rest#9]
Hi!

I think this package is really really useful. Keystone.js together with this is a very nice system for rapid prototyping. There's two things I have a question about though:
- I haven't put anything in production yet with Keystone.js but the eventual concern would of course be authentication and authorization. Can keystone-rest use authentication?
- Being able to do server side pagination out of the box would be awesome. Does keystone-rest do that?

**Comment by danielpquinn** [comment]
Before you commit to keystone-rest, I suggest you take a look at baucis (https://github.com/wprl/baucis), which is a much more stable and robust rest api generation tool for mongoose.

You could add authorization middleware to your route definitions, but the middleware itself is up to you to implement. Check out the passport bearer strategy documentation for examples of how you might do this: https://github.com/jaredhanson/passport-http-bearer

When a list of items is returned I add a 'total' header to the response. So to do pagination you basically do something like this:

/api/models?limit=10&skip=10

The 'total' response header might be 100, in which case you would be on page two of ten.

**Comment by Industrial** [comment]
Thanks a lot! I'm eventually looking to implement the REST interface over websockets as a RPC API. I'd like to integrate the authentication/authorization there too. I'm very far from having any to show though, just ideas for now :-)
